.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH MOZPLUGGER-CONTROLLER 1 "February 23, 2004"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
mozplugger-controller \- a helper application to mozplugger
.SH SYNOPSIS
.B mozplugger-controller
.RI internal-options
.SH DESCRIPTION
\fBmozplugger-controller\fP is a helper application for mozplugger(7) that
gives controls to some audio streaming plugins (Play, Pause, Stop).
It is launched by the mozplugger plugin and is \fBnot\fP intended to be run
directly.
.SH SEE ALSO
.BR mozplugger (7).
.SH AUTHOR
Fredrik H\[:u]binette, hubbe@hubbe.net
.br
Louis Bavoil, louis@bavoil.net
.PP
This manual page was prepared by Bernard Blackham <bernard@blackham.com.au>
for the Debian GNU/Linux system (but may be used by others).
